name: Terraform demo-$(Build.BuildId)

trigger: 
  branches:
    include:
    - master

stages:
  
- stage: TerraformInit
  displayName: Terraform Init
  jobs:
  - job: TerraformInit
    displayName: Terraform Init
    steps:
    - task: TerraformTaskV1@0
      displayName: Terraform init
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: 'aws'
        backendServiceAWS: 'aws-service-connection'
        backendAWSBucketName: 'hybrid-demo'
        backendAWSKey: 'tf/terraform.tfstate'        

- stage: TerraformPlan
  displayName: Terraform Plan
  jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    steps:
    - task: TerraformTaskV1@0
      inputs:
        provider: 'aws'
        command: 'plan'
        workingDirectory: 'aws'
        environmentServiceNameAWS: 'aws-service-connection'