name: Terraform demo-$(Build.BuildId)

trigger: 
  branches:
    include:
    - master

stages:
# - stage: BuildArtifact
#   displayName: Build Artifact
#   jobs:
#   - job: AwsArtifact
#     displayName: Build AWS Artifact
#     steps:
#     - template: /devops/templates/publish-artifact.yml
#       parameters:                               
#         cloudProvider: 'aws'  

- stage: TerraformPlan
  displayName: Terraform Plan
  jobs:
    - job: AwsArtifact
      displayName: Build AWS Artifact
      steps:
      - task: TerraformTaskV1@0
        displayName: Terraform init
        inputs:
          provider: 'aws'
          command: 'init'
          workingDirectory: 'aws'
          backendServiceAWS: 'aws-service-connection'
          backendAWSBucketName: 'hybrid-demo'
          backendAWSKey: 'tf/terraform.tfstate'        

      - template: /devops/templates/terraform-plan.yml
        parameters:                               
          cloudProvider: 'aws'