name: Terraform demo-$(Build.BuildId)

trigger: 
  branches:
    include:
    - master

stages:

- stage: TerraformValidate
  displayName: Terraform Validate
  jobs:
  - job: TerraformValidate
    displayName: Terraform Validate
    steps:
    - task: TerraformTaskV1@0
      displayName: Terraform Validate
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: 'aws'
        backendServiceAWS: 'aws-service-connection'
        backendAWSBucketName: 'hybrid-demo'
        backendAWSKey: 'tf/terraform.tfstate'        

- stage: TerraformDeploy
  displayName: Terraform Deploy
  jobs:
  - job: TerraformDeploy
    displayName: Terraform Deploy
    steps:
    - task: TerraformTaskV1@0
      displayName: Terraform Init
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: 'aws'
        backendServiceAWS: 'aws-service-connection'
        backendAWSBucketName: 'hybrid-demo'
        backendAWSKey: 'tf/terraform.tfstate'

    - task: TerraformTaskV1@0
      displayName: Terraform Plan
      inputs:
        provider: 'aws'
        command: 'plan'
        workingDirectory: 'aws'
        environmentServiceNameAWS: 'aws-service-connection'

    - task: TerraformTaskV1@0
      displayName: Terraform Apply
      enabled: true
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: 'aws'
        environmentServiceNameAWS: 'aws-service-connection'

    - task: TerraformTaskV1@0
      displayName: Terraform Destroy
      enabled: false
      inputs:
        provider: 'aws'
        command: 'destroy'
        workingDirectory: 'aws'
        environmentServiceNameAWS: 'aws-service-connection'