name: Terraform demo-$(Build.BuildId)

trigger: 
  branches:
    include:
    - master

stages:
# - stage: BuildArtifact
#   displayName: Build Artifact
#   jobs:
#   - job: AwsArtifact
#     displayName: Build AWS Artifact
#     steps:
#     - template: /devops/templates/publish-artifact.yml
#       parameters:                               
#         cloudProvider: 'aws'  

- stage: TerraformPlan
  displayName: Terraform Plan
  jobs:
    - job: AwsArtifact
      displayName: Build AWS Artifact
      steps:
      - template: /devops/templates/terraform-plan.yml
        parameters:                               
          cloudProvider: 'aws'