name: Terraform demo-$(Build.BuildId

trigger: 
  branches:
    include:
    - master

stages:
- stage: BuildArtifact
  displayName: Build Artifact
  jobs:
  - job: AwsArtifact
    displayName: Build AWS Artifact
    steps:
    - template: /devops/templates/publish-artifact.yml
      parameters:                               
        providerName: 'aws'  

  # - job: AzureArtifact
  #   displayName: Build Azure Artifact
  #   steps:
  #   - task: PublishBuildArtifacts@1
  #     displayName: 'Publish Terraform Artifact'
  #     inputs:
  #       PathtoPublish: 'azure'
  #       ArtifactName: azure-artifact

  # - job: GcpArtifact
  #   displayName: Build GCP Artifact
  #   steps:
  #   - task: PublishBuildArtifacts@1
  #     displayName: 'Publish Terraform Artifact'
  #     inputs:
  #       PathtoPublish: 'gcp'
  #       ArtifactName: gcp-artifact        