parameters:
- name: cloudProvider
  type: string

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Terraform Artifact'
  inputs:
    PathtoPublish: '${{ parameters.cloudProvider }}'
    ArtifactName: ${{ parameters.cloudProvider }}-artifact