parameters:
- name: providerName
  type: string

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Terraform Artifact'
  inputs:
    PathtoPublish: '${{ parameters.providerName }}'
    ArtifactName: ${{ parameters.providerName }}-artifact