parameters:
- name: cloudProvider
  type: string

steps:

- task: TerraformTaskV1@0
  inputs:
    provider: '${{ parameters.cloudProvider }}'
    command: 'plan'
    workingDirectory: '${{ parameters.cloudProvider }}'
    environmentServiceNameAWS: '${{ parameters.cloudProvider }}-service-connection'
