parameters:
- name: cloudProvider
  type: string

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.3'

- task: TerraformTaskV1@0
  inputs:
    provider: '${{ parameters.cloudProvider }}'
    command: 'plan'
    workingDirectory: '${{ parameters.cloudProvider }}'
    environmentServiceNameAWS: '${{ parameters.cloudProvider }}-service-connection'
